name:                sequence-converter
version:             0.1.0.0
github:              "githubuser/sequence-converter"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/sequence-converter#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3 && < 2

library:
  source-dirs: src

executables:
  sequence-converter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequence-converter

tests:
  sequence-converter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequence-converter
    - hspec >= 2.4.8 && < 3
